create header and add favicon
coders-camp-2021-best-team/TeamUp-Client pull request #22
Opened 2022-04-04 18:33 UTC by Mariusz-web

2022-04-04 19:13 UTC, Veryyapeee requested changes

2022-04-04 19:13 UTC, Veryyapeee commented on src/components/Header/Header.tsx
> +                    <div>
We don't do div in here 8)

2022-04-04 19:13 UTC, Veryyapeee commented on src/components/Header/Header.tsx
> +                                <Link
styles and logic kinda repeats, extract that to separate component (Atom)

2022-04-04 19:13 UTC, Veryyapeee commented on src/components/Header/Header.tsx
> +    const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
just import useState from react

2022-04-04 19:13 UTC, Veryyapeee commented on src/components/Header/Header.tsx
> +import * as React from 'react';
since react 16.x we don't need to import * from react

2022-04-04 19:13 UTC, Veryyapeee commented on src/components/Header/Header.tsx
> +    const open = Boolean(anchorEl);
what do you need this for?
You don't need that reassign in here

2022-04-04 19:13 UTC, Veryyapeee commented on src/components/Header/Header.tsx
> +                            aria-controls={open ? 'basic-menu' : undefined}
Couldn't you just
`open && 'basic-menu'`

2022-04-04 19:13 UTC, Veryyapeee commented on src/screens/Home/Home.tsx
> +            <Header />
why is it here? It's already included in <Base/> where it belongs

2022-04-07 17:20 UTC, Veryyapeee requested changes

2022-04-07 17:20 UTC, Veryyapeee commented on src/components/Atoms/Navigation.tsx
> +type NAV_ITEM = {
Type should start just with capital letter, what you did here is convention for constants

2022-04-07 17:20 UTC, Veryyapeee commented on src/components/Atoms/Navigation.tsx
> +const NAV_ITEMS = [
Just
navItems

2022-04-07 17:21 UTC, Veryyapeee commented
https://user-images.githubusercontent.com/43120132/162260805-ec3533ec-9b4a-4978-a579-9c5faff0e95f.MOV

Looks kinda buggy on preview

2022-04-07 17:59 UTC, Veryyapeee approved these changes
Approved, looks ok I think, please just fix these two small comments

2022-04-07 17:59 UTC, Veryyapeee commented on src/components/Atoms/Navigation.tsx
> +const NAV_ITEMS = [
You didn't changed that line
`navItems`

2022-04-07 17:59 UTC, Veryyapeee commented on src/components/Atoms/Navigation.tsx
> +type navItem = {
`NavItem`

2022-04-07 19:35 UTC, T0ffik approved these changes

2022-04-07 19:36 UTC, merged