feat: Create profile screen
coders-camp-2021-best-team/TeamUp-Client pull request #23
Opened 2022-04-06 21:39 UTC by KonTra7cf

2022-04-11 08:28 UTC, Mariusz-web approved these changes

2022-04-12 14:27 UTC, Veryyapeee requested changes

2022-04-12 14:27 UTC, Veryyapeee commented on src/components/Profile/desktop.tsx
> +export const DesktopProfile = () => {
Do you have to split that logic for two separate components?

2022-04-12 14:27 UTC, Veryyapeee commented on src/components/Profile/UserProfile.tsx
> +export const UserProfile = () => {
You should add TODO comment and create issue for conntecting that screen to API

2022-04-14 18:03 UTC, Veryyapeee requested changes

2022-04-14 18:03 UTC, Veryyapeee commented on src/components/Profile/UserProfile.tsx
> +export const UserProfile = () => {
I don't see created issue, which should be linked in here

Also please answer in the conversation always after making changes

2022-04-21 09:30 UTC, PoProstuMieciek requested changes
I fixed the integration with API, but profile looks bad.
User avatar should not be streched. Just crop it or keep the aspect ratio.

![image](https://user-images.githubusercontent.com/44976946/164425179-42855470-f1e7-439a-85ae-4c3568fee411.png)

2022-04-21 12:19 UTC, KonTra7cf commented
@PoProstuMieciek - I've added property to crop the image so now it should be fine

2022-04-22 08:13 UTC, PoProstuMieciek approved these changes
I removed the desktop layout as it was not working. Also I simplified components structure. Approved!

2022-04-22 08:16 UTC, T0ffik approved these changes

2022-04-22 08:22 UTC, Veryyapeee approved these changes

2022-04-22 08:23 UTC, merged