Issue 12 feat/UI create signin signup screen
coders-camp-2021-best-team/TeamUp-Client pull request #32
Opened 2022-04-12 20:57 UTC by T0ffik

2022-04-21 10:18 UTC, PoProstuMieciek requested changes
I added form handling with React Hook Form and API integration. Please add components for displaying errors to user.

2022-04-22 10:00 UTC, T0ffik commented on src/screens/Register/Register.tsx
> -                                    display: 'block'
without this style input on focus look like this, so I think that this should stay
![image](https://user-images.githubusercontent.com/85763715/164684151-c015ef85-6989-4949-85f3-d271a2ef30a9.png)

2022-04-22 10:04 UTC, PoProstuMieciek commented on src/screens/Register/Register.tsx
> -                                    display: 'block'
it shouldn't be done like that
material ui css selectors are random at each build, find another way of doing it

maybe just leave it for now

2022-04-22 10:05 UTC, PoProstuMieciek commented
ok im done lets finish this task

2022-04-22 10:05 UTC, PoProstuMieciek approved these changes

2022-04-22 10:07 UTC, Mariusz-web approved these changes

2022-04-22 10:08 UTC, merged